version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4293ad4
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
    ports:
      - 5432:5432

  app:
    image: django
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - BASE_URL= 'http://localhost:8000/'
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgdata:
    external: true