# Generated by Django 4.1 on 2022-10-30 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num', models.IntegerField(verbose_name='N° Apartamento')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Aparamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'apartamentos',
                'ordering': ['fk_predio', 'num'],
            },
        ),
        migrations.CreateModel(
            name='Condomino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=15, null=True, verbose_name='RG')),
                ('orgao_emissor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Orgão emissor')),
                ('sexo', models.CharField(choices=[(1, 'Masculino'), (2, 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('profissao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('tel_residencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. Residência')),
                ('tel_celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. Celular')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('proprietario', models.BooleanField(default=False, verbose_name='Proprietário')),
                ('morador', models.BooleanField(default=False, verbose_name='Morador')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Condômino',
                'verbose_name_plural': 'Condôminos',
                'db_table': 'condomino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=15, verbose_name='Placa veículo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora saída')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('fk_apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.apartamento')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
                'ordering': ['fk_apartamento', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=255, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=45, verbose_name='Cor')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('fk_apartamento', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='condominio.apartamento')),
                ('fk_condomino_morador', models.ForeignKey(blank=True, limit_choices_to={'morador': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.condomino')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculos',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num', models.IntegerField(unique=True, verbose_name='N° Prédio')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('sub_sindico', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='condominio.condomino')),
            ],
            options={
                'verbose_name': 'Prédio',
                'verbose_name_plural': 'Prédios',
                'db_table': 'predios',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data saída')),
                ('responsavel', models.BooleanField(default=False, verbose_name='Responsável')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('fk_apartamento', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.apartamento')),
                ('fk_condomino_morador', models.ForeignKey(blank=True, limit_choices_to={'morador': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartamento_morador', to='condominio.condomino')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'db_table': 'morador',
                'ordering': ['fk_apartamento'],
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='fk_condomino_proprietario',
            field=models.ForeignKey(blank=True, limit_choices_to={'proprietario': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.condomino'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='fk_predio',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='condominio.predio'),
        ),
        migrations.AlterUniqueTogether(
            name='apartamento',
            unique_together={('num', 'fk_predio')},
        ),
    ]
