# Generated by Django 4.1 on 2022-10-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_apartamento_obs_alter_morador_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomino',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='sexo',
            field=models.CharField(choices=[(1, 'Masculino'), (2, 'Feminino')], max_length=5, verbose_name='Sexo'),
        ),
    ]
