# Generated by Django 4.1 on 2022-10-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_alter_condomino_obs_alter_condomino_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomino',
            name='dependente',
            field=models.BooleanField(default=False, verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='cpf',
            field=models.CharField(blank=True, help_text='Registro caracteres especiais.', max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='orgao_emissor',
            field=models.CharField(blank=True, help_text='Registro caracteres especiais.', max_length=15, null=True, verbose_name='Orgão emissor'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='rg',
            field=models.CharField(blank=True, help_text='Registro caracteres especiais.', max_length=15, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=5, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='tel_celular',
            field=models.CharField(blank=True, help_text='xx-xxxx-xxxx', max_length=15, null=True, verbose_name='Tel. Celular'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fk_condomino_morador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.condomino'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Registro caracteres especiais.', max_length=15, unique=True, verbose_name='Placa'),
        ),
    ]
