# Generated by Django 4.1 on 2022-10-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_condomino_dependente_alter_condomino_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['fk_apartamento', 'fk_condomino_morador__nome'], 'verbose_name': 'Morador', 'verbose_name_plural': 'Moradores'},
        ),
        migrations.AddField(
            model_name='visitante',
            name='cracha_veiculo',
            field=models.BooleanField(default=True, verbose_name='Devolução crachá veículo'),
        ),
    ]
