# Generated by Django 4.1 on 2022-10-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emb_site',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
