# Generated by Django 4.1 on 2022-10-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_profile_cn_remove_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['criado']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='vlr_status',
            new_name='status',
        ),
    ]
